require('dotenv').config();
const express=require('express'),http=require('http'),cors=require('cors'),path=require('path'),fs=require('fs'),multer=require('multer');
const {Server}=require('socket.io');const {read,write,id,now}=require('./db');const {sign,hash,compare,auth,verify}=require('./auth');const {stkPush}=require('./mpesa');
const app=express(),server=http.createServer(app),io=new Server(server,{cors:{origin:process.env.CORS_ORIGIN||'*',methods:['GET','POST','PATCH','DELETE']}}),PORT=Number(process.env.PORT||3000),HOST=process.env.HOST||'0.0.0.0';
const rateBuckets=new Map();
function rateLimit(key,limit=120,windowMs=60000){const nowMs=Date.now(),b=rateBuckets.get(key)||{start:nowMs,count:0};if(nowMs-b.start>windowMs){b.start=nowMs;b.count=0}b.count++;rateBuckets.set(key,b);return b.count<=limit}
function adminOnly(req,res,next){const email=String(process.env.ADMIN_EMAIL||'').trim().toLowerCase();if(!email||String(req.user?.email||'').toLowerCase()!==email)return res.status(403).json({error:'Administrator access required'});next()}
app.disable('x-powered-by');
app.use((req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','SAMEORIGIN');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('Permissions-Policy','camera=(self), microphone=(self)');if(req.path.startsWith('/api/')&&!rateLimit(`${req.ip}:${req.path}`,180,60000))return res.status(429).json({error:'Too many requests. Please try again shortly.'});next()});
const uploadDir=process.env.NEXORA_UPLOAD_DIR ? path.resolve(process.env.NEXORA_UPLOAD_DIR) : path.join(__dirname,'uploads');fs.mkdirSync(uploadDir,{recursive:true});
app.use(cors({origin:process.env.CORS_ORIGIN||'*'}));app.use(express.json({limit:'8mb'}));app.use(express.urlencoded({extended:true}));app.use('/uploads',express.static(uploadDir));app.use(express.static(path.join(__dirname,'..','public'),{etag:false,maxAge:0,setHeaders:(res)=>res.setHeader('Cache-Control','no-store')}));
const allowed=new Set(['image/jpeg','image/png','image/webp','image/gif','video/mp4','video/webm','application/pdf','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','application/vnd.ms-powerpoint','application/vnd.openxmlformats-officedocument.presentationml.presentation']);
const storage=multer.diskStorage({destination:uploadDir,filename:(req,file,cb)=>{const safe=file.originalname.replace(/[^a-zA-Z0-9._-]/g,'_');cb(null,`${Date.now()}-${Math.random().toString(36).slice(2)}-${safe}`)}});
const upload=multer({storage,limits:{fileSize:100*1024*1024,files:10},fileFilter:(req,file,cb)=>allowed.has(file.mimetype)?cb(null,true):cb(new Error('Unsupported file type'))});
function publicUser(u){if(!u)return null;return{id:u.id,name:u.name,email:u.email,avatar:u.avatar||'',bio:u.bio||'',skills:u.skills||[],education:u.education||'',work:u.work||'',website:u.website||'',premium:!!u.premium,admin:!!(process.env.ADMIN_EMAIL&&String(u.email).toLowerCase()===String(process.env.ADMIN_EMAIL).toLowerCase()),followers:(u.followers||[]).length,following:(u.following||[]).length}}
function getUser(db,uid){return db.users.find(u=>u.id===uid)}
function notify(db,userId,type,text,meta={}){db.notifications=db.notifications||[];db.notifications.unshift({id:id('note'),userId,type,text,meta,read:false,createdAt:now()})}
function cleanUserForList(db,u,me){return {...publicUser(u),following:(getUser(db,me)?.following||[]).includes(u.id)}}
app.get('/api/health',(req,res)=>res.json({ok:true,app:'NEXORA',version:'13.0.0',time:now()}));
app.post('/api/auth/register',async(req,res)=>{try{const{name,email,password}=req.body||{};if(!String(name||'').trim()||!String(email||'').trim()||String(password||'').length<6)return res.status(400).json({error:'Name, email and password (6+ characters) are required'});const db=read(),clean=String(email).trim().toLowerCase();if(db.users.some(u=>u.email===clean))return res.status(409).json({error:'Email already registered'});const user={id:id('usr'),name:String(name).trim().slice(0,80),email:clean,passwordHash:await hash(password),bio:'',avatar:'',premium:false,followers:[],following:[],blocked:[],createdAt:now()};db.users.push(user);write(db);res.json({token:sign(user),user:publicUser(user)})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/auth/login',async(req,res)=>{try{const db=read(),email=String(req.body?.email||'').trim().toLowerCase(),u=db.users.find(x=>x.email===email);if(!u||!(await compare(String(req.body?.password||''),u.passwordHash)))return res.status(401).json({error:'Invalid email or password'});db.loginEvents=db.loginEvents||[];db.loginEvents.push({id:id('login'),userId:u.id,action:'login',createdAt:now()});db.sessions=db.sessions||[];db.sessions.push({id:id('ses'),userId:u.id,createdAt:now()});write(db);res.json({token:sign(u),user:publicUser(u)})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/me',auth,(req,res)=>{const u=getUser(read(),req.user.id);if(!u)return res.status(404).json({error:'User not found'});res.json({user:publicUser(u)})});
app.patch('/api/me',auth,(req,res)=>{const db=read(),u=getUser(db,req.user.id);if(!u)return res.status(404).json({error:'User not found'});if(typeof req.body.name==='string'&&req.body.name.trim())u.name=req.body.name.trim().slice(0,80);if(typeof req.body.bio==='string')u.bio=req.body.bio.slice(0,500);if(Array.isArray(req.body.skills))u.skills=req.body.skills.map(x=>String(x).trim()).filter(Boolean).slice(0,20);if(typeof req.body.education==='string')u.education=req.body.education.slice(0,300);if(typeof req.body.work==='string')u.work=req.body.work.slice(0,300);if(typeof req.body.website==='string')u.website=req.body.website.slice(0,300);write(db);res.json({user:publicUser(u)})});
app.post('/api/me/avatar',auth,upload.single('avatar'),(req,res)=>{if(!req.file)return res.status(400).json({error:'Select an image'});const db=read(),u=getUser(db,req.user.id);u.avatar=`/uploads/${req.file.filename}`;write(db);res.json({user:publicUser(u)})});
app.get('/api/users',auth,(req,res)=>{const db=read(),q=String(req.query.q||'').toLowerCase(),me=getUser(db,req.user.id);res.json({users:db.users.filter(u=>u.id!==req.user.id&&!(me.blocked||[]).includes(u.id)&&(!q||u.name.toLowerCase().includes(q)||u.email.includes(q))).slice(0,50).map(u=>cleanUserForList(db,u,req.user.id))})});
app.get('/api/search',auth,(req,res)=>{const db=read(),q=String(req.query.q||'').toLowerCase().trim(),me=getUser(db,req.user.id),blocked=me.blocked||[];res.json({users:db.users.filter(u=>u.id!==req.user.id&&!blocked.includes(u.id)&&(!q||u.name.toLowerCase().includes(q)||u.email.includes(q))).slice(0,20).map(u=>cleanUserForList(db,u,req.user.id)),groups:db.groups.filter(g=>!q||`${g.name} ${g.category||''}`.toLowerCase().includes(q)).slice(0,20),opportunities:db.opportunities.filter(o=>!q||`${o.title} ${o.category} ${o.type}`.toLowerCase().includes(q)).slice(0,20),listings:db.listings.filter(l=>!q||`${l.title} ${l.category}`.toLowerCase().includes(q)).slice(0,20),events:db.events.filter(e=>!q||e.title.toLowerCase().includes(q)).slice(0,20)})});
app.post('/api/users/:id/follow',auth,(req,res)=>{const db=read(),me=getUser(db,req.user.id),t=getUser(db,req.params.id);if(!t||t.id===me.id)return res.status(404).json({error:'User not found'});if((me.blocked||[]).includes(t.id))return res.status(403).json({error:'Unblock this member first'});me.following=me.following||[];t.followers=t.followers||[];const on=me.following.includes(t.id);if(on){me.following=me.following.filter(x=>x!==t.id);t.followers=t.followers.filter(x=>x!==me.id)}else{me.following.push(t.id);t.followers.push(me.id);notify(db,t.id,'follow',`${me.name} started following you`,{userId:me.id})}write(db);res.json({following:!on})});
app.get('/api/posts',auth,(req,res)=>{const db=read(),me=getUser(db,req.user.id),blocked=me.blocked||[];res.json({posts:db.posts.filter(p=>!blocked.includes(p.authorId)).slice().sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(p=>({...p,author:publicUser(getUser(db,p.authorId)),likesCount:(p.likes||[]).length,liked:(p.likes||[]).includes(req.user.id),saved:(p.saves||[]).includes(req.user.id),comments:(p.comments||[]).map(c=>({...c,user:publicUser(getUser(db,c.userId))}))}))})});
app.post('/api/posts',auth,upload.array('files',10),(req,res)=>{const db=read(),files=(req.files||[]).map(f=>({name:f.originalname,type:f.mimetype,size:f.size,url:`/uploads/${f.filename}`})),text=String(req.body.text||'').slice(0,5000);if(!text&&!files.length)return res.status(400).json({error:'Write something or attach a file'});const p={id:id('post'),authorId:req.user.id,text,files,likes:[],comments:[],saves:[],shares:0,createdAt:now()};db.posts.push(p);awardXP(db,req.user.id,5,'new post');write(db);io.emit('post:new',p);res.status(201).json({post:p})});
app.patch('/api/posts/:id',auth,(req,res)=>{const db=read(),p=db.posts.find(x=>x.id===req.params.id);if(!p)return res.status(404).json({error:'Post not found'});if(p.authorId!==req.user.id)return res.status(403).json({error:'You can only edit your own post'});p.text=String(req.body.text||'').slice(0,5000);p.updatedAt=now();write(db);res.json({ok:true})});
app.delete('/api/posts/:id',auth,(req,res)=>{const db=read(),i=db.posts.findIndex(x=>x.id===req.params.id);if(i<0)return res.status(404).json({error:'Post not found'});if(db.posts[i].authorId!==req.user.id)return res.status(403).json({error:'You can only delete your own post'});db.posts.splice(i,1);write(db);res.json({ok:true})});
app.post('/api/posts/:id/like',auth,(req,res)=>{const db=read(),p=db.posts.find(x=>x.id===req.params.id);if(!p)return res.status(404).json({error:'Post not found'});p.likes=p.likes||[];const liked=p.likes.includes(req.user.id);p.likes=liked?p.likes.filter(x=>x!==req.user.id):p.likes.concat(req.user.id);if(!liked&&p.authorId!==req.user.id)notify(db,p.authorId,'like',`${getUser(db,req.user.id).name} liked your post`,{postId:p.id});write(db);res.json({liked:!liked,likesCount:p.likes.length})});
app.post('/api/posts/:id/comment',auth,(req,res)=>{const db=read(),p=db.posts.find(x=>x.id===req.params.id),text=String(req.body.text||'').trim();if(!p||!text)return res.status(400).json({error:'Post and comment are required'});const c={id:id('com'),userId:req.user.id,text:text.slice(0,1000),createdAt:now()};p.comments=p.comments||[];p.comments.push(c);if(p.authorId!==req.user.id)notify(db,p.authorId,'comment',`${getUser(db,req.user.id).name} commented on your post`,{postId:p.id});write(db);res.status(201).json({comment:{...c,user:publicUser(getUser(db,req.user.id))}})});
app.post('/api/posts/:id/share',auth,(req,res)=>{const db=read(),p=db.posts.find(x=>x.id===req.params.id);if(!p)return res.status(404).json({error:'Post not found'});p.shares=(p.shares||0)+1;write(db);res.json({shares:p.shares})});
app.post('/api/posts/:id/save',auth,(req,res)=>{const db=read(),p=db.posts.find(x=>x.id===req.params.id);if(!p)return res.status(404).json({error:'Post not found'});p.saves=p.saves||[];const saved=p.saves.includes(req.user.id);p.saves=saved?p.saves.filter(x=>x!==req.user.id):p.saves.concat(req.user.id);write(db);res.json({saved:!saved})});
app.get('/api/saved',auth,(req,res)=>{const db=read();res.json({posts:db.posts.filter(p=>(p.saves||[]).includes(req.user.id)).map(p=>({...p,author:publicUser(getUser(db,p.authorId)),likesCount:(p.likes||[]).length}))})});
app.get('/api/groups',auth,(req,res)=>{const db=read();res.json({groups:db.groups.map(g=>({...g,membersCount:(g.members||[]).length,joined:(g.members||[]).includes(req.user.id)}))})});
app.post('/api/groups',auth,(req,res)=>{const name=String(req.body.name||'').trim();if(!name)return res.status(400).json({error:'Community name required'});const db=read(),g={id:id('grp'),name:name.slice(0,100),description:String(req.body.description||'').slice(0,500),category:String(req.body.category||'General').slice(0,60),ownerId:req.user.id,members:[req.user.id],createdAt:now()};db.groups.push(g);write(db);res.status(201).json({group:g})});
app.post('/api/groups/:id/join',auth,(req,res)=>{const db=read(),g=db.groups.find(x=>x.id===req.params.id);if(!g)return res.status(404).json({error:'Community not found'});g.members=g.members||[];const joined=g.members.includes(req.user.id);g.members=joined?g.members.filter(x=>x!==req.user.id):g.members.concat(req.user.id);write(db);res.json({joined:!joined,membersCount:g.members.length})});
app.get('/api/groups/:id/messages',auth,(req,res)=>{const db=read(),g=db.groups.find(x=>x.id===req.params.id);if(!g||!(g.members||[]).includes(req.user.id))return res.status(403).json({error:'Join the community to view chat'});res.json({messages:(db.messages||[]).filter(m=>m.groupId===g.id).slice(-300).map(m=>({...m,user:publicUser(getUser(db,m.userId))}))})});
app.get('/api/messages/:userId',auth,(req,res)=>{const db=read(),uid=req.params.userId;if(!getUser(db,uid))return res.status(404).json({error:'Recipient not found'});res.json({messages:(db.directMessages||[]).filter(m=>(m.fromId===req.user.id&&m.toId===uid)||(m.fromId===uid&&m.toId===req.user.id)).slice(-300).map(m=>({...m,user:publicUser(getUser(db,m.fromId))}))})});
app.post('/api/messages/:userId',auth,(req,res)=>{const text=String(req.body.text||'').trim(),db=read(),to=getUser(db,req.params.userId),me=getUser(db,req.user.id);if(!to||!text)return res.status(400).json({error:'Recipient and message are required'});if((me.blocked||[]).includes(to.id)||(to.blocked||[]).includes(me.id))return res.status(403).json({error:'Messaging is unavailable between these members'});db.directMessages=db.directMessages||[];const m={id:id('dm'),fromId:req.user.id,toId:to.id,text:text.slice(0,2000),createdAt:now()};db.directMessages.push(m);notify(db,to.id,'message',`${me.name} sent you a message`,{userId:me.id});write(db);const out={...m,user:publicUser(me)};const sid=online.get(to.id);if(sid)io.to(sid).emit('direct:message',out);res.status(201).json({message:out})});
app.post('/api/notifications/read',auth,(req,res)=>{const db=read();(db.notifications||[]).filter(n=>n.userId===req.user.id).forEach(n=>n.read=true);write(db);res.json({ok:true})});
function listEndpoint(key){return(req,res)=>{const db=read(),q=String(req.query.q||'').toLowerCase();res.json({items:(db[key]||[]).filter(x=>!q||JSON.stringify(x).toLowerCase().includes(q)).slice().reverse()})}}
app.get('/api/opportunities',auth,listEndpoint('opportunities'));
app.post('/api/opportunities',auth,(req,res)=>{const{title,description,category,type,location,remote,deadline}=req.body||{};if(!String(title||'').trim())return res.status(400).json({error:'Opportunity title required'});const db=read(),o={id:id('opp'),title:String(title).slice(0,120),description:String(description||'').slice(0,3000),category:String(category||'General'),type:String(type||'Job'),location:String(location||''),remote:!!remote,deadline:deadline||'',ownerId:req.user.id,createdAt:now()};db.opportunities.push(o);write(db);res.status(201).json({item:o})});
app.post('/api/opportunities/:id/apply',auth,(req,res)=>{const db=read(),o=db.opportunities.find(x=>x.id===req.params.id);if(!o)return res.status(404).json({error:'Opportunity not found'});db.applications=db.applications||[];if(db.applications.some(a=>a.opportunityId===o.id&&a.userId===req.user.id))return res.status(409).json({error:'Already applied'});db.applications.push({id:id('app'),opportunityId:o.id,userId:req.user.id,message:String(req.body.message||'').slice(0,1000),createdAt:now()});if(o.ownerId!==req.user.id)notify(db,o.ownerId,'application',`${getUser(db,req.user.id).name} applied for ${o.title}`,{opportunityId:o.id});write(db);res.json({ok:true})});
app.get('/api/applications',auth,(req,res)=>{const db=read();res.json({applications:(db.applications||[]).filter(a=>a.userId===req.user.id||db.opportunities.some(o=>o.id===a.opportunityId&&o.ownerId===req.user.id)).map(a=>({...a,opportunity:db.opportunities.find(o=>o.id===a.opportunityId),user:publicUser(getUser(db,a.userId))}))})});
app.get('/api/listings',auth,listEndpoint('listings'));
app.post('/api/listings',auth,upload.array('images',6),(req,res)=>{const{title,description,price,category,location}=req.body||{};if(!String(title||'').trim())return res.status(400).json({error:'Listing title required'});const db=read(),l={id:id('lst'),title:String(title).slice(0,120),description:String(description||'').slice(0,2000),price:Number(price||0),category:String(category||'General'),location:String(location||''),sellerId:req.user.id,images:(req.files||[]).map(f=>`/uploads/${f.filename}`),createdAt:now()};db.listings.push(l);write(db);res.status(201).json({item:l})});
app.get('/api/events',auth,listEndpoint('events'));
app.post('/api/events',auth,(req,res)=>{const{title,description,date,location,online,capacity}=req.body||{};if(!String(title||'').trim()||!date)return res.status(400).json({error:'Event title and date required'});const db=read(),e={id:id('evt'),title:String(title).slice(0,120),description:String(description||'').slice(0,2000),date,location:String(location||''),online:!!online,capacity:Number(capacity||0),attendees:[req.user.id],hostId:req.user.id,createdAt:now()};db.events.push(e);write(db);res.status(201).json({item:e})});
app.post('/api/events/:id/rsvp',auth,(req,res)=>{const db=read(),e=db.events.find(x=>x.id===req.params.id);if(!e)return res.status(404).json({error:'Event not found'});e.attendees=e.attendees||[];const yes=e.attendees.includes(req.user.id);if(yes)e.attendees=e.attendees.filter(x=>x!==req.user.id);else{if(e.capacity&&e.attendees.length>=e.capacity)return res.status(409).json({error:'Event is full'});e.attendees.push(req.user.id)}write(db);res.json({going:!yes,count:e.attendees.length})});
app.get('/api/stories',auth,(req,res)=>{const db=read();db.stories=db.stories||[];const cutoff=Date.now()-86400000;db.stories=db.stories.filter(s=>!s.expiresAt||new Date(s.expiresAt).getTime()>cutoff);write(db);res.json({stories:db.stories.slice().reverse().map(s=>({...s,author:publicUser(getUser(db,s.authorId))}))})});
app.post('/api/stories',auth,upload.single('file'),(req,res)=>{const db=read();db.stories=db.stories||[];const s={id:id('story'),authorId:req.user.id,text:String(req.body.text||'').slice(0,500),files:req.file?[{name:req.file.originalname,type:req.file.mimetype,url:`/uploads/${req.file.filename}`}]:[],createdAt:now(),expiresAt:new Date(Date.now()+86400000).toISOString()};if(!s.text&&!s.files.length)return res.status(400).json({error:'Add a caption or media'});db.stories.push(s);write(db);res.status(201).json({story:{...s,author:publicUser(getUser(db,req.user.id))}})});
app.get('/api/education',auth,(req,res)=>{const db=read();db.courseProgress=db.courseProgress||{};const base=[{id:'c1',title:'Digital Skills Starter',category:'Technology',level:'Beginner'},{id:'c2',title:'Entrepreneurship Essentials',category:'Business',level:'Beginner'},{id:'c3',title:'Career & CV Mastery',category:'Career',level:'All levels'},{id:'c4',title:'Personal Finance Basics',category:'Finance',level:'Beginner'}];res.json({courses:base.map(c=>({...c,progress:Number(db.courseProgress[`${req.user.id}:${c.id}`]||0)}))})});
app.post('/api/education/:id/progress',auth,(req,res)=>{const db=read();db.courseProgress=db.courseProgress||{};const key=`${req.user.id}:${req.params.id}`,p=Math.min(100,Number(db.courseProgress[key]||0)+25);db.courseProgress[key]=p;write(db);res.json({course:{id:req.params.id,progress:p}})});
app.get('/api/premium/status',auth,(req,res)=>{const u=getUser(read(),req.user.id);res.json({premium:!!u.premium,premiumAt:u.premiumAt||null})});
app.post('/api/payments/mpesa/stk',auth,async(req,res)=>{let phone=String(req.body.phone||'').replace(/\s+/g,'');if(/^0[17]\d{8}$/.test(phone))phone='254'+phone.slice(1);const amount=Number(req.body.amount||100);if(!/^254[17]\d{8}$/.test(phone))return res.status(400).json({error:'Use 07XXXXXXXX, 01XXXXXXXX or 2547XXXXXXXX format'});if(amount!==100)return res.status(400).json({error:'NEXORA Premium costs KSh 100/month'});try{const response=await stkPush(phone,amount,`NEXORA-${req.user.id}`);const db=read();db.payments=db.payments||[];db.payments.push({id:id('pay'),userId:req.user.id,phone,amount,checkoutRequestId:response.CheckoutRequestID||null,merchantRequestId:response.MerchantRequestID||null,response,status:'pending',createdAt:now()});write(db);res.json({ok:true,response})}catch(e){res.status(503).json({error:e.message})}});
app.post('/api/payments/mpesa/callback',(req,res)=>{const cb=req.body?.Body?.stkCallback,db=read();if(!cb)return res.json({ResultCode:0,ResultDesc:'Accepted'});const p=(db.payments||[]).slice().reverse().find(x=>x.checkoutRequestId===cb.CheckoutRequestID);if(p){p.status=cb.ResultCode===0?'paid':'failed';p.callback=cb;if(cb.ResultCode===0){const u=getUser(db,p.userId);if(u){u.premium=true;u.premiumAt=now()}}}write(db);res.json({ResultCode:0,ResultDesc:'Accepted'})});
app.get('/api/payments/history',auth,(req,res)=>{const db=read();res.json({payments:(db.payments||[]).filter(p=>p.userId===req.user.id).slice().reverse().map(p=>({id:p.id,amount:p.amount,status:p.status,createdAt:p.createdAt}))})});
app.post('/api/report',auth,(req,res)=>{const db=read();db.reports=db.reports||[];db.reports.push({id:id('report'),userId:req.user.id,targetId:req.body.targetId||null,reason:String(req.body.reason||'No reason').slice(0,1000),createdAt:now()});notify(db,req.user.id,'report','Your report has been received. Thank you.',{});write(db);res.json({ok:true,message:'Thanks. Your report has been recorded.'})});
app.post('/api/block/:id',auth,(req,res)=>{const db=read(),u=getUser(db,req.user.id),target=getUser(db,req.params.id);if(!target)return res.status(404).json({error:'Member not found'});u.blocked=u.blocked||[];const on=u.blocked.includes(target.id);u.blocked=on?u.blocked.filter(x=>x!==target.id):u.blocked.concat(target.id);if(!on){u.following=(u.following||[]).filter(x=>x!==target.id);target.followers=(target.followers||[]).filter(x=>x!==u.id)}write(db);res.json({blocked:!on})});
app.get('/api/settings',auth,(req,res)=>{const db=read(),u=getUser(db,req.user.id);res.json({settings:{notifications:u.settings?.notifications!==false,private:!!u.settings?.private}})});
app.patch('/api/settings',auth,(req,res)=>{const db=read(),u=getUser(db,req.user.id);u.settings={...(u.settings||{}),notifications:req.body.notifications!==false,private:!!req.body.private};write(db);res.json({settings:u.settings})});
app.get('/api/export',auth,(req,res)=>{const db=read(),uid=req.user.id;res.json({user:publicUser(getUser(db,uid)),posts:db.posts.filter(p=>p.authorId===uid),groups:db.groups.filter(g=>(g.members||[]).includes(uid)),messages:(db.directMessages||[]).filter(m=>m.fromId===uid||m.toId===uid),applications:(db.applications||[]).filter(a=>a.userId===uid),listings:db.listings.filter(l=>l.sellerId===uid),events:db.events.filter(e=>e.hostId===uid),stories:(db.stories||[]).filter(s=>s.authorId===uid),payments:(db.payments||[]).filter(p=>p.userId===uid)})});
const online=new Map();
io.use((socket,next)=>{try{socket.user=verify(socket.handshake.auth?.token);next()}catch{next(new Error('Unauthorized'))}});
io.on('connection',socket=>{online.set(socket.user.id,socket.id);socket.emit('presence:list',[...online.keys()]);socket.broadcast.emit('presence:update',{userId:socket.user.id,online:true});socket.on('group:join',gid=>socket.join(`group:${gid}`));socket.on('group:message',({groupId,text})=>{const db=read(),g=db.groups.find(x=>x.id===groupId),t=String(text||'').trim();if(!g||!(g.members||[]).includes(socket.user.id)||!t)return;db.messages=db.messages||[];const m={id:id('msg'),groupId,userId:socket.user.id,text:t.slice(0,2000),createdAt:now()};db.messages.push(m);write(db);io.to(`group:${groupId}`).emit('group:message',{...m,user:publicUser(getUser(db,socket.user.id))})});socket.on('typing',({to,typing})=>{const sid=online.get(to);if(sid)io.to(sid).emit('typing',{from:socket.user.id,typing:!!typing})});socket.on('call:offer',({to,offer})=>online.get(to)&&io.to(online.get(to)).emit('call:offer',{from:socket.user.id,fromName:socket.user.name,offer}));socket.on('call:answer',({to,answer})=>online.get(to)&&io.to(online.get(to)).emit('call:answer',{from:socket.user.id,answer}));socket.on('call:ice',({to,candidate})=>online.get(to)&&io.to(online.get(to)).emit('call:ice',{from:socket.user.id,candidate}));socket.on('call:end',({to})=>online.get(to)&&io.to(online.get(to)).emit('call:end',{from:socket.user.id}));socket.on('disconnect',()=>{if(online.get(socket.user.id)===socket.id)online.delete(socket.user.id);socket.broadcast.emit('presence:update',{userId:socket.user.id,online:false})})});

// Advanced account, moderation, discovery and lifecycle features.
app.get('/api/users/:id',auth,(req,res)=>{const db=read(),u=getUser(db,req.params.id),me=getUser(db,req.user.id);if(!u)return res.status(404).json({error:'Member not found'});if((me.blocked||[]).includes(u.id))return res.status(403).json({error:'Member is blocked'});res.json({user:{...publicUser(u),following:(me.following||[]).includes(u.id),isMe:u.id===me.id}})});
app.get('/api/users/:id/followers',auth,(req,res)=>{const db=read(),u=getUser(db,req.params.id);if(!u)return res.status(404).json({error:'Member not found'});res.json({users:(u.followers||[]).map(x=>getUser(db,x)).filter(Boolean).map(x=>publicUser(x))})});
app.get('/api/users/:id/following',auth,(req,res)=>{const db=read(),u=getUser(db,req.params.id);if(!u)return res.status(404).json({error:'Member not found'});res.json({users:(u.following||[]).map(x=>getUser(db,x)).filter(Boolean).map(x=>publicUser(x))})});
app.post('/api/me/password',auth,async(req,res)=>{const db=read(),u=getUser(db,req.user.id),current=String(req.body.currentPassword||''),next=String(req.body.newPassword||'');if(next.length<8)return res.status(400).json({error:'New password must be at least 8 characters'});if(!(await compare(current,u.passwordHash)))return res.status(401).json({error:'Current password is incorrect'});u.passwordHash=await hash(next);u.passwordChangedAt=now();write(db);res.json({ok:true,message:'Password changed successfully'})});
app.delete('/api/me',auth,async(req,res)=>{const db=read(),uid=req.user.id,u=getUser(db,uid);if(!u)return res.status(404).json({error:'User not found'});if(!(await compare(String(req.body.password||''),u.passwordHash)))return res.status(401).json({error:'Password confirmation failed'});db.users=db.users.filter(x=>x.id!==uid);db.posts=db.posts.filter(x=>x.authorId!==uid);db.groups=db.groups.filter(x=>x.ownerId!==uid);db.opportunities=db.opportunities.filter(x=>x.ownerId!==uid);db.listings=db.listings.filter(x=>x.sellerId!==uid);db.events=db.events.filter(x=>x.hostId!==uid);db.stories=db.stories.filter(x=>x.authorId!==uid);db.directMessages=db.directMessages.filter(x=>x.fromId!==uid&&x.toId!==uid);db.applications=db.applications.filter(x=>x.userId!==uid);db.notifications=db.notifications.filter(x=>x.userId!==uid);for(const other of db.users){other.followers=(other.followers||[]).filter(x=>x!==uid);other.following=(other.following||[]).filter(x=>x!==uid);other.blocked=(other.blocked||[]).filter(x=>x!==uid)}write(db);res.json({ok:true})});
app.get('/api/conversations',auth,(req,res)=>{const db=read(),uid=req.user.id,seen=new Map();for(const m of db.directMessages){if(m.fromId!==uid&&m.toId!==uid)continue;const other=m.fromId===uid?m.toId:m.fromId;const old=seen.get(other);if(!old||m.createdAt>old.createdAt)seen.set(other,m)}res.json({conversations:[...seen.entries()].map(([other,last])=>({user:publicUser(getUser(db,other)),lastMessage:{text:last.text,createdAt:last.createdAt},unread:db.directMessages.filter(m=>m.fromId===other&&m.toId===uid&&!m.read).length})).filter(x=>x.user).sort((a,b)=>b.lastMessage.createdAt.localeCompare(a.lastMessage.createdAt))})});
app.post('/api/messages/:userId/read',auth,(req,res)=>{const db=read(),uid=req.user.id,other=req.params.userId;db.directMessages.forEach(m=>{if(m.fromId===other&&m.toId===uid)m.read=true});write(db);res.json({ok:true})});
app.post('/api/posts/:id/comments/:commentId/delete',auth,(req,res)=>{const db=read(),p=db.posts.find(x=>x.id===req.params.id);if(!p)return res.status(404).json({error:'Post not found'});const i=(p.comments||[]).findIndex(c=>c.id===req.params.commentId);if(i<0)return res.status(404).json({error:'Comment not found'});if(p.comments[i].userId!==req.user.id&&p.authorId!==req.user.id)return res.status(403).json({error:'Not allowed'});p.comments.splice(i,1);write(db);res.json({ok:true})});
app.get('/api/notifications/unread-count',auth,(req,res)=>{const db=read();res.json({count:db.notifications.filter(n=>n.userId===req.user.id&&!n.read).length})});
app.post('/api/notifications/:id/read',auth,(req,res)=>{const db=read(),n=db.notifications.find(x=>x.id===req.params.id&&x.userId===req.user.id);if(!n)return res.status(404).json({error:'Notification not found'});n.read=true;write(db);res.json({ok:true})});
app.delete('/api/notifications/:id',auth,(req,res)=>{const db=read();const before=db.notifications.length;db.notifications=db.notifications.filter(x=>!(x.id===req.params.id&&x.userId===req.user.id));if(before===db.notifications.length)return res.status(404).json({error:'Notification not found'});write(db);res.json({ok:true})});
app.patch('/api/listings/:id',auth,upload.array('images',6),(req,res)=>{const db=read(),l=db.listings.find(x=>x.id===req.params.id);if(!l)return res.status(404).json({error:'Listing not found'});if(l.sellerId!==req.user.id)return res.status(403).json({error:'Only the seller can edit this listing'});for(const k of ['title','description','category','location'])if(typeof req.body[k]==='string')l[k]=req.body[k].slice(0,k==='description'?2000:120);if(req.body.price!==undefined)l.price=Math.max(0,Number(req.body.price||0));if(req.files?.length)l.images=(req.files||[]).map(f=>`/uploads/${f.filename}`);l.updatedAt=now();write(db);res.json({item:l})});
app.delete('/api/listings/:id',auth,(req,res)=>{const db=read(),i=db.listings.findIndex(x=>x.id===req.params.id);if(i<0)return res.status(404).json({error:'Listing not found'});if(db.listings[i].sellerId!==req.user.id)return res.status(403).json({error:'Only the seller can delete this listing'});db.listings.splice(i,1);write(db);res.json({ok:true})});
app.patch('/api/opportunities/:id',auth,(req,res)=>{const db=read(),o=db.opportunities.find(x=>x.id===req.params.id);if(!o)return res.status(404).json({error:'Opportunity not found'});if(o.ownerId!==req.user.id)return res.status(403).json({error:'Only the owner can edit this opportunity'});for(const k of ['title','description','category','type','location','deadline'])if(typeof req.body[k]==='string')o[k]=req.body[k].slice(0,k==='description'?3000:120);if(req.body.remote!==undefined)o.remote=!!req.body.remote;o.updatedAt=now();write(db);res.json({item:o})});
app.delete('/api/opportunities/:id',auth,(req,res)=>{const db=read(),i=db.opportunities.findIndex(x=>x.id===req.params.id);if(i<0)return res.status(404).json({error:'Opportunity not found'});if(db.opportunities[i].ownerId!==req.user.id)return res.status(403).json({error:'Only the owner can delete this opportunity'});db.opportunities.splice(i,1);db.applications=db.applications.filter(a=>a.opportunityId!==req.params.id);write(db);res.json({ok:true})});
app.delete('/api/events/:id',auth,(req,res)=>{const db=read(),i=db.events.findIndex(x=>x.id===req.params.id);if(i<0)return res.status(404).json({error:'Event not found'});if(db.events[i].hostId!==req.user.id)return res.status(403).json({error:'Only the host can delete this event'});db.events.splice(i,1);write(db);res.json({ok:true})});
app.delete('/api/stories/:id',auth,(req,res)=>{const db=read(),i=db.stories.findIndex(x=>x.id===req.params.id);if(i<0)return res.status(404).json({error:'Story not found'});if(db.stories[i].authorId!==req.user.id)return res.status(403).json({error:'Only the author can delete this story'});db.stories.splice(i,1);write(db);res.json({ok:true})});
app.post('/api/groups/:id/messages',auth,(req,res)=>{const db=read(),g=db.groups.find(x=>x.id===req.params.id),text=String(req.body.text||'').trim();if(!g||!(g.members||[]).includes(req.user.id))return res.status(403).json({error:'Join the community first'});if(!text)return res.status(400).json({error:'Message cannot be empty'});const m={id:id('msg'),groupId:g.id,userId:req.user.id,text:text.slice(0,2000),createdAt:now()};db.messages.push(m);write(db);io.to(`group:${g.id}`).emit('group:message',{...m,user:publicUser(getUser(db,req.user.id))});res.status(201).json({message:m})});
app.delete('/api/groups/:id',auth,(req,res)=>{const db=read(),i=db.groups.findIndex(x=>x.id===req.params.id);if(i<0)return res.status(404).json({error:'Community not found'});if(db.groups[i].ownerId!==req.user.id)return res.status(403).json({error:'Only the owner can delete this community'});const gid=db.groups[i].id;db.groups.splice(i,1);db.messages=db.messages.filter(m=>m.groupId!==gid);write(db);res.json({ok:true})});
app.get('/api/dashboard',auth,(req,res)=>{const db=read(),uid=req.user.id;res.json({stats:{posts:db.posts.filter(x=>x.authorId===uid).length,followers:(getUser(db,uid)?.followers||[]).length,following:(getUser(db,uid)?.following||[]).length,listings:db.listings.filter(x=>x.sellerId===uid).length,opportunities:db.opportunities.filter(x=>x.ownerId===uid).length,events:db.events.filter(x=>x.hostId===uid).length,applications:db.applications.filter(x=>x.userId===uid).length,messages:db.directMessages.filter(x=>x.fromId===uid||x.toId===uid).length}})});
app.get('/api/admin/stats',auth,adminOnly,(req,res)=>{const db=read();res.json({stats:{users:db.users.length,posts:db.posts.length,groups:db.groups.length,opportunities:db.opportunities.length,listings:db.listings.length,events:db.events.length,stories:db.stories.length,reports:db.reports.length,supportTickets:db.supportTickets.length,payments:db.payments.length,orders:db.orders.length,reviews:db.reviews.length}})});
app.get('/api/admin/reports',auth,adminOnly,(req,res)=>{const db=read();res.json({reports:db.reports.slice().reverse().map(r=>({...r,user:publicUser(getUser(db,r.userId))}))})});
app.patch('/api/admin/reports/:id',auth,adminOnly,(req,res)=>{const db=read(),r=db.reports.find(x=>x.id===req.params.id);if(!r)return res.status(404).json({error:'Report not found'});r.status=String(req.body.status||'reviewed').slice(0,40);r.reviewedAt=now();write(db);res.json({ok:true})});
app.get('/api/admin/support',auth,adminOnly,(req,res)=>{const db=read();res.json({tickets:db.supportTickets.slice().reverse().map(t=>({...t,user:publicUser(getUser(db,t.userId))}))})});
app.patch('/api/admin/support/:id',auth,adminOnly,(req,res)=>{const db=read(),t=db.supportTickets.find(x=>x.id===req.params.id);if(!t)return res.status(404).json({error:'Ticket not found'});t.status=String(req.body.status||'closed').slice(0,40);t.updatedAt=now();write(db);res.json({ok:true})});
app.get('/api/admin/users',auth,adminOnly,(req,res)=>{const db=read();res.json({users:db.users.map(u=>publicUser(u))})});

app.use((err,req,res,next)=>{if(err?.code==='LIMIT_FILE_SIZE')return res.status(413).json({error:'File too large (maximum 100 MB)'});if(err?.message==='Unsupported file type')return res.status(415).json({error:err.message});console.error(err);res.status(500).json({error:'Server error'})});

// V9 feature layer: AI helper, wallet/orders, richer social tools, security center and analytics.
function ownerOnly(db, collection, itemId, uid, field){const x=(db[collection]||[]).find(v=>v.id===itemId);return x && x[field]===uid}
app.get('/api/analytics/me',auth,(req,res)=>{const db=read(),uid=req.user.id;const posts=db.posts.filter(p=>p.authorId===uid);res.json({analytics:{posts:posts.length,likes:posts.reduce((n,p)=>n+(p.likes||[]).length,0),comments:posts.reduce((n,p)=>n+(p.comments||[]).length,0),shares:posts.reduce((n,p)=>n+(p.shares||0),0),followers:(getUser(db,uid)?.followers||[]).length,orders:db.orders.filter(o=>o.buyerId===uid||o.sellerId===uid).length,revenue:db.orders.filter(o=>o.sellerId===uid&&o.status!=='cancelled').reduce((n,o)=>n+Number(o.total||0),0)}})});
app.get('/api/wallet',auth,(req,res)=>{const db=read(),uid=req.user.id,tx=db.payments.filter(p=>p.userId===uid||p.buyerId===uid||p.sellerId===uid).slice().sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));res.json({wallet:{balance:0,currency:'KES',transactions:tx}})});
app.get('/api/orders',auth,(req,res)=>{const db=read(),uid=req.user.id;res.json({orders:db.orders.filter(o=>o.buyerId===uid||o.sellerId===uid).map(o=>({...o,item:db.listings.find(l=>l.id===o.listingId),buyer:publicUser(getUser(db,o.buyerId)),seller:publicUser(getUser(db,o.sellerId))})).reverse()})});
app.post('/api/listings/:id/order',auth,(req,res)=>{const db=read(),l=db.listings.find(x=>x.id===req.params.id);if(!l)return res.status(404).json({error:'Listing not found'});if(l.sellerId===req.user.id)return res.status(400).json({error:'You cannot order your own listing'});const qty=Math.max(1,Math.min(99,Number(req.body.qty||1)));const total=Number(l.price||0)*qty;const o={id:id('ord'),listingId:l.id,buyerId:req.user.id,sellerId:l.sellerId,qty,total,currency:'KES',status:'pending',createdAt:now()};db.orders.push(o);notify(db,l.sellerId,'order',`${getUser(db,req.user.id).name} placed an order for ${l.title}`,{orderId:o.id});write(db);res.status(201).json({order:o})});
app.patch('/api/orders/:id/status',auth,(req,res)=>{const db=read(),o=db.orders.find(x=>x.id===req.params.id);if(!o)return res.status(404).json({error:'Order not found'});if(o.sellerId!==req.user.id&&o.buyerId!==req.user.id)return res.status(403).json({error:'Not allowed'});const allowed=['pending','confirmed','processing','shipped','delivered','cancelled'];const st=String(req.body.status||'pending');if(!allowed.includes(st))return res.status(400).json({error:'Invalid order status'});if(o.status==='delivered'&&st!=='delivered')return res.status(400).json({error:'Delivered orders cannot be changed'});o.status=st;o.updatedAt=now();write(db);res.json({order:o})});
app.post('/api/listings/:id/reviews',auth,(req,res)=>{const db=read(),l=db.listings.find(x=>x.id===req.params.id);if(!l)return res.status(404).json({error:'Listing not found'});const rating=Math.max(1,Math.min(5,Number(req.body.rating||5))),text=String(req.body.text||'').trim().slice(0,1000);if(!text)return res.status(400).json({error:'Review text is required'});if(db.reviews.some(r=>r.listingId===l.id&&r.userId===req.user.id))return res.status(409).json({error:'You already reviewed this listing'});const r={id:id('rev'),listingId:l.id,userId:req.user.id,rating,text,createdAt:now()};db.reviews.push(r);write(db);res.status(201).json({review:{...r,user:publicUser(getUser(db,req.user.id))}})});
app.get('/api/listings/:id/reviews',auth,(req,res)=>{const db=read();res.json({reviews:db.reviews.filter(r=>r.listingId===req.params.id).map(r=>({...r,user:publicUser(getUser(db,r.userId))})).reverse()})});
app.post('/api/posts/:id/reaction',auth,(req,res)=>{const db=read(),p=db.posts.find(x=>x.id===req.params.id);if(!p)return res.status(404).json({error:'Post not found'});const types=['like','love','laugh','wow','sad','angry'],type=String(req.body.type||'like');if(!types.includes(type))return res.status(400).json({error:'Invalid reaction'});db.postReactions=db.postReactions||[];const old=db.postReactions.find(r=>r.postId===p.id&&r.userId===req.user.id);if(old){if(old.type===type)db.postReactions=db.postReactions.filter(r=>r!==old);else old.type=type}else db.postReactions.push({id:id('react'),postId:p.id,userId:req.user.id,type,createdAt:now()});write(db);res.json({reactions:db.postReactions.filter(r=>r.postId===p.id).reduce((a,r)=>(a[r.type]=(a[r.type]||0)+1,a),{})})});
app.post('/api/posts/:id/comments/:commentId/reply',auth,(req,res)=>{const db=read(),p=db.posts.find(x=>x.id===req.params.id),c=(p?.comments||[]).find(x=>x.id===req.params.commentId),text=String(req.body.text||'').trim();if(!p||!c||!text)return res.status(400).json({error:'Post, comment and reply are required'});c.replies=c.replies||[];const r={id:id('reply'),userId:req.user.id,text:text.slice(0,1000),createdAt:now()};c.replies.push(r);write(db);res.status(201).json({reply:{...r,user:publicUser(getUser(db,req.user.id))}})});
app.get('/api/security',auth,(req,res)=>{const db=read(),u=getUser(db,req.user.id);res.json({security:{verified:!!u.verified,twoFactor:!!u.twoFactorEnabled,activeSessions:db.sessions.filter(s=>s.userId===u.id).length,loginEvents:db.loginEvents.filter(x=>x.userId===u.id).slice(-20).reverse()}})});
app.post('/api/security/verify',auth,(req,res)=>{const db=read(),u=getUser(db,req.user.id);u.verified=true;write(db);res.json({verified:true,message:'Account marked verified in local mode. Connect an email/SMS provider for production verification.'})});
app.post('/api/security/2fa',auth,(req,res)=>{const db=read(),u=getUser(db,req.user.id),enabled=!!req.body.enabled;u.twoFactorEnabled=enabled;write(db);res.json({enabled,message:enabled?'2FA preference enabled. Add a TOTP/SMS provider before production launch.':'2FA preference disabled.'})});
app.post('/api/security/logout-sessions',auth,(req,res)=>{const db=read();db.sessions=db.sessions.filter(s=>s.userId!==req.user.id);write(db);res.json({ok:true})});
function timeOfDayGreeting(){const h=new Date().getHours();if(h<5)return'burning the midnight oil';if(h<12)return'Good morning';if(h<17)return'Good afternoon';if(h<21)return'Good evening';return'Good night'}
function xpLevel(xp){return Math.floor((xp||0)/100)+1}
function awardXP(db,userId,amount,reason){const u=getUser(db,userId);if(!u)return;u.xp=(u.xp||0)+amount;const newLevel=xpLevel(u.xp);if(newLevel>(u.level||1)){notify(db,userId,'levelup',`🎉 You reached Level ${newLevel} on NEXORA!`,{level:newLevel})}u.level=newLevel;return{xp:u.xp,level:u.level,gained:amount,reason}}
function buildAIReply(db,user,rawMessage){
  const q=String(rawMessage||'').trim();
  const x=q.toLowerCase();
  const suggestions=[];
  let answer=null;
  const greetRe=/^(hi|hello|hey|yo|sup|good (morning|afternoon|evening)|howdy)\b/;
  const thanksRe=/\b(thanks|thank you|thx|appreciate)\b/;
  const helpRe=/^(what can you do|help|help me|capabilities|features|who are you)\??$/;
  if(greetRe.test(x)){
    const streak=user.streak||0;
    answer=`${timeOfDayGreeting()}, ${user.name.split(' ')[0]}! 👋 ${streak>0?`You're on a ${streak}-day streak — keep it going! `:''}What are you in the mood for today — jobs, the marketplace, learning, or just catching up on your feed?`;
    suggestions.push('Find work for me','Show trending posts','Check my streak');
  }else if(thanksRe.test(x)){
    answer=`Anytime, ${user.name.split(' ')[0]}! I'm always here if you need to navigate NEXORA, get unstuck, or just want ideas. 🙌`;
  }else if(helpRe.test(x)){
    answer='I\'m your NEXORA guide. I can help you find jobs and gigs, buy or sell in the marketplace, plan your learning, catch up on messages, manage premium/payments, stay safe, and track your streak, XP and leaderboard rank. Just ask naturally — like "find me remote work" or "what\'s trending?".';
    suggestions.push('Find work for me','How do I sell something?','Show leaderboard');
  }else if(/streak|check.?in|\bxp|\blevel|\bpoints|\bbadge/.test(x)){
    const streak=user.streak||0,xp=user.xp||0,level=xpLevel(xp);
    const today=now().slice(0,10);
    const checkedInToday=db.checkins.some(c=>c.userId===user.id&&c.date===today);
    answer=`🔥 Streak: ${streak} day${streak===1?'':'s'}\n⭐ Level ${level} (${xp} XP)\n${checkedInToday?'You already checked in today — nice!':'You haven\'t checked in today yet — do that to keep your streak alive.'}`;
    suggestions.push(checkedInToday?'Show leaderboard':'Daily check-in');
  }else if(/leaderboard|\brank|top user|who.?s winning/.test(x)){
    const top=db.users.slice().sort((a,b)=>(b.xp||0)-(a.xp||0)).slice(0,3).map((u,i)=>`${i+1}. ${u.name} — ${u.xp||0} XP`).join('\n');
    answer=top?`🏆 Top NEXORA members right now:\n${top}\n\nOpen the Leaderboard to see the full ranking and your own position.`:'🏆 The leaderboard is quiet right now — be one of the first to earn XP by checking in daily and staying active!';
    suggestions.push('Open Leaderboard');
  }else if(/communit(y|ies)|\bgroup/.test(x)){
    answer=`👥 There are ${db.groups.length} communities on NEXORA. Join one that matches your interests, or start your own around a topic you care about.`;
    suggestions.push('Open Communities');
  }else if(/\bevent|\brsvp\b|meetup/.test(x)){
    const upcoming=db.events.filter(e=>!e.date||new Date(e.date)>=new Date()).length;
    answer=`📅 There ${upcoming===1?'is':'are'} ${upcoming} upcoming event${upcoming===1?'':'s'}. Open Events to RSVP, or host your own in a couple of taps.`;
    suggestions.push('Open Events');
  }else if(/\bpremium\b|\bpayment|mpesa|subscri/.test(x)){
    answer=user.premium?'💎 You\'re already a NEXORA Premium member — thank you for supporting the platform! Check Wallet for your payment history.':'NEXORA Premium is KSh 100/month via M-Pesa STK Push. Open Premium/Wallet, enter your phone number, and approve the prompt on your phone. Production use needs real Safaricom Daraja credentials configured by the site owner.';
    suggestions.push('Open Wallet');
  }else if(/\bsafe\b|\breport|\bblock|security|password|2fa/.test(x)){
    answer='🛡️ Your safety matters. Use Safety to report content or block someone — it\'s private and reviewed by admins. In Settings → Security you can change your password, enable a 2FA preference, and sign other sessions out.';
    suggestions.push('Open Safety','Open Settings');
  }else if(/\bmessag|\bchat\b|\bcall\b|\bdm\b|conversation/.test(x)){
    const unread=db.directMessages.filter(m=>m.toId===user.id&&!m.read).length;
    answer=unread?`✉️ You have ${unread} unread message${unread===1?'':'s'} waiting. Open Messages to catch up.`:'Your inbox is all caught up! Open Messages to start a new conversation — text, and where supported, voice/video calling too.';
    suggestions.push('Open Messages');
  }else if(/\bprofile|\bbio\b|\bavatar|edit my/.test(x)){
    answer='👤 Open Profile to update your photo, bio, skills, education and work history. A complete profile gets more followers and better opportunity matches.';
    suggestions.push('Open Profile');
  }else if(/\btrend|\bpopular|\bexplore|what.?s (new|happening)/.test(x)){
    const trending=db.posts.slice().sort((a,b)=>((b.likes||[]).length+(b.comments||[]).length)-((a.likes||[]).length+(a.comments||[]).length)).slice(0,3);
    answer=trending.length?`📈 Trending on NEXORA right now:\n${trending.map(p=>`• "${(p.text||'[media]').slice(0,60)}" — ${(p.likes||[]).length} likes`).join('\n')}\n\nOpen Explore to see more.`:'Nothing trending yet — be the first to post something great!';
    suggestions.push('Open Explore');
  }else if(/stud(y|ies)|\bcourse|education|\blearn|\bskill/.test(x)){
    const progressEntries=Object.entries(db.courseProgress||{}).filter(([k])=>k.startsWith(`${user.id}:`));
    const started=progressEntries.length;
    const avg=started?Math.round(progressEntries.reduce((n,[,v])=>n+Number(v||0),0)/started):0;
    answer=started?`🎓 You've started ${started} course${started===1?'':'s'} with ${avg}% average progress. Keep chipping away — every lesson gives you momentum.`:'Open Education to start a course — Digital Skills, Entrepreneurship, Career & CV Mastery, or Personal Finance. Small daily progress beats cramming.';
    suggestions.push('Open Education');
  }else if(/\bmarket|\bsell|\bbuy\b|\bproduct|\bshop|\blisting/.test(x)){
    const listings=db.listings.slice().sort((a,b)=>b.createdAt.localeCompare(a.createdAt));
    const top=listings.slice(0,3).map(l=>`• ${l.title} — KSh ${l.price}`).join('\n');
    answer=`🛒 The Marketplace has ${listings.length} active listing${listings.length===1?'':'s'}.${top?`\n\nJust added:\n${top}`:''}\n\nTo sell: open Marketplace → New Listing, add photos and a price. To buy: open a listing and place an order or message the seller.`;
    suggestions.push('Open Marketplace','Create a listing');
  }else if(/\bjob|\bwork\b|\bcareer|\bintern|\bhire|\bfreelance|\bgig/.test(x)){
    const open=db.opportunities.slice().sort((a,b)=>b.createdAt.localeCompare(a.createdAt));
    const top=open.slice(0,3).map(o=>`• ${o.title}${o.remote?' (remote)':''}`).join('\n');
    answer=`💼 There ${open.length===1?'is':'are'} currently ${open.length} opportunit${open.length===1?'y':'ies'} posted.${top?`\n\nMost recent:\n${top}`:''}\n\nOpen Opportunities, filter by Jobs, Freelance or Internships, and tap Apply on anything that fits.`;
    suggestions.push('Open Opportunities','Post an opportunity');
  }else{
    answer='✦ I can help with jobs, the marketplace, education, messages, premium/payments, safety, communities, events, your profile, or your streak/XP and the leaderboard. What would you like to do?';
    suggestions.push('Find work for me','Show trending posts','Check my streak');
  }
  return{answer,suggestions};
}
async function externalAI(db,user,q,mode){
  const key=String(process.env.NEXORA_AI_API_KEY||'').trim();
  if(!key)return null;
  const base=String(process.env.NEXORA_AI_BASE_URL||'https://api.openai.com/v1').replace(/\/$/,'');
  const model=String(process.env.NEXORA_AI_MODEL||'').trim();
  if(!model)return null;
  const history=(db.aiChats||[]).filter(x=>x.userId===user.id).slice(-12).flatMap(x=>[
    {role:'user',content:String(x.message||'').replace(/^\[Mode: [^\]]+\] /,'')},
    {role:'assistant',content:String(x.answer||'')}
  ]);
  const system=`You are NEXORA, a warm, capable AI companion inside a social app. Talk naturally like a modern general-purpose assistant. You can help with everyday conversation, decisions, planning, writing, jobs, marketplace, communities, messaging, learning and life. Do not pretend to have performed actions you cannot perform. If a request requires live app data, explain what you can access. Be concise but useful. Current NEXORA mode: ${mode||'Companion'}. User name: ${user.name||'there'}.`;
  const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),30000);
  try{
    const r=await fetch(base+'/chat/completions',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+key},body:JSON.stringify({model,messages:[{role:'system',content:system},...history,{role:'user',content:q}],temperature:0.7,max_tokens:900}),signal:controller.signal});
    const data=await r.json().catch(()=>({}));
    if(!r.ok)throw new Error(data?.error?.message||`AI provider returned ${r.status}`);
    const answer=String(data?.choices?.[0]?.message?.content||'').trim();
    if(!answer)throw new Error('AI provider returned an empty response');
    return answer;
  }finally{clearTimeout(timer)}
}
app.post('/api/ai',auth,async(req,res)=>{const db=read(),q=String(req.body.message||'').trim().slice(0,4000),mode=String(req.body.mode||'Companion').slice(0,30);if(!q)return res.status(400).json({error:'Message required'});const user=getUser(db,req.user.id);try{let answer=await externalAI(db,user,q,mode);if(!answer){const fallback=buildAIReply(db,user,q);answer=fallback.answer;var suggestions=fallback.suggestions}else suggestions=[];db.aiChats=db.aiChats||[];db.aiChats.push({id:id('ai'),userId:req.user.id,message:q,answer,mode,createdAt:now()});db.aiChats=db.aiChats.slice(-1000);write(db);res.json({answer,suggestions,provider:process.env.NEXORA_AI_API_KEY?'live':'local'})}catch(e){console.error('AI error:',e.message);res.status(502).json({error:'NEXORA AI could not reach the configured AI service. Check the AI settings and try again.'})}});
app.delete('/api/ai/history',auth,(req,res)=>{const db=read();db.aiChats=(db.aiChats||[]).filter(x=>x.userId!==req.user.id);write(db);res.json({ok:true})});
app.get('/api/checkin',auth,(req,res)=>{const db=read(),user=getUser(db,req.user.id),today=now().slice(0,10);const checkedInToday=db.checkins.some(c=>c.userId===req.user.id&&c.date===today);res.json({checkedInToday,streak:user.streak||0,longestStreak:user.longestStreak||0,xp:user.xp||0,level:xpLevel(user.xp||0)})});
app.post('/api/checkin',auth,(req,res)=>{
  const db=read(),user=getUser(db,req.user.id),today=now().slice(0,10);
  const already=db.checkins.some(c=>c.userId===req.user.id&&c.date===today);
  if(already){return res.json({ok:true,alreadyCheckedIn:true,streak:user.streak||0,longestStreak:user.longestStreak||0,xp:user.xp||0,level:xpLevel(user.xp||0)})}
  const yesterday=new Date(Date.now()-86400000).toISOString().slice(0,10);
  const hadYesterday=db.checkins.some(c=>c.userId===req.user.id&&c.date===yesterday);
  user.streak=hadYesterday?(user.streak||0)+1:1;
  user.longestStreak=Math.max(user.longestStreak||0,user.streak);
  const bonus=Math.min(user.streak,10)*2;
  const gain=10+bonus;
  const before=xpLevel(user.xp||0);
  db.checkins.push({id:id('checkin'),userId:req.user.id,date:today,createdAt:now()});
  const result=awardXP(db,req.user.id,gain,'daily check-in');
  if(user.streak>0&&user.streak%7===0)notify(db,req.user.id,'streak',`🔥 ${user.streak}-day streak! You're on fire.`,{streak:user.streak});
  write(db);
  res.json({ok:true,alreadyCheckedIn:false,streak:user.streak,longestStreak:user.longestStreak,xp:user.xp,xpGained:gain,level:result.level,leveledUp:result.level>before});
});
app.get('/api/leaderboard',auth,(req,res)=>{
  const db=read();
  const ranked=db.users.slice().sort((a,b)=>(b.xp||0)-(a.xp||0)).slice(0,20).map((u,i)=>({rank:i+1,id:u.id,name:u.name,avatar:u.avatar||'',xp:u.xp||0,level:xpLevel(u.xp||0),streak:u.streak||0}));
  const meIndex=db.users.slice().sort((a,b)=>(b.xp||0)-(a.xp||0)).findIndex(u=>u.id===req.user.id);
  res.json({leaderboard:ranked,myRank:meIndex+1,myXp:getUser(db,req.user.id)?.xp||0});
});
app.get('/api/ai/history',auth,(req,res)=>{const db=read();res.json({messages:db.aiChats.filter(x=>x.userId===req.user.id).slice(-50)})});
app.get('/api/notifications',auth,(req,res)=>{const db=read();res.json({notifications:db.notifications.filter(n=>n.userId===req.user.id).slice(0,100)})});
app.post('/api/support',auth,(req,res)=>{const db=read(),subject=String(req.body.subject||'').trim().slice(0,120),text=String(req.body.text||'').trim().slice(0,2000);if(!subject||!text)return res.status(400).json({error:'Subject and message are required'});const t={id:id('ticket'),userId:req.user.id,subject,text,status:'open',createdAt:now()};db.supportTickets.push(t);write(db);res.status(201).json({ticket:t})});
app.get('/api/support',auth,(req,res)=>{const db=read();res.json({tickets:db.supportTickets.filter(t=>t.userId===req.user.id).reverse()})});

app.get('*',(req,res)=>req.path.startsWith('/api/')?res.status(404).json({error:'API route not found'}):res.sendFile(path.join(__dirname,'..','public','index.html')));
server.listen(PORT,HOST,()=>console.log(`NEXORA v13 running on http://${HOST}:${PORT}`));
